name: End-to-End Tests

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  e2e-test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v2
        with:
          go-version: 1.16

      - name: Run E2E tests
        run: ./test/e2e/run.sh
